### ISSUE TITLE
coloring of shebang comment line and preprocessor lines missing

### ISSUE THREAD

**Issue by michelemartone** [ahf/cocci-syntax#9]
Hello Alexander.
Thanks for making work with Coccinelle in Vim more colorful.

I think it would be nice to have lines as the shebang comment line (e.g. `#spatch --c++...`) and the preprocessor lines (e.g. `#include <iostream>`) colored as well.

**Comment by ahf** [comment]
All done here. Thanks again for the contribution.

Out of curiosity, why did this suddenly come up? Yesterday I had a couple of bug fixes and feature enhancements as pull-requests to this project here on GitHub and the project has otherwise been dormant for years.

**Comment by michelemartone** [comment]
Yesterday I learnt of the update to `cocci-syntax` and noticed that these syntax bits are yet uncovered, so I added my two cents.
It's nice to make Coccinelle usable; the other day I tried integrating it in Compiler Explorer (see https://github.com/compiler-explorer/compiler-explorer/pull/7001 ) but I fear these syntax files won't do there.

**Comment by ahf** [comment]
Ah. I see. It's not related to Hacktober or anything like that?

**Comment by michelemartone** [comment]
Nope :-)
